#!/bin/bash

# Build motors_controller arduino sketch
# see https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc

script_dir=$(dirname "$0")

cd $script_dir/build_esp32

arduino --verify --board arduino:avr:pro:cpu=16MHzatmega328 --verbose motors_controller.ino
