version: "3"
name: "solar_concentrator"

services:
  dev:
    image: image_solar_concentrator:latest
    build: .
    working_dir: /solar_concentrator
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix   # required for UI started from container to be viewed on host
      - /var/run/dbus:/var/run/dbus     # required for avahi tools to success when launched from the container
      - ..:/solar_concentrator
      - ./config:/root/.config          # map configs to be saved in host WARNING : individual permissions must be enabled in Dockerfile (see kdeveloprc)
      - ./local:/root/.local            # map configs to be saved in host
      - ../../kde_builder/kf5-qt5/volumes/kde/usr_working:/kde/usr_working
    networks:
      - no-internet          # no internet connection by default, use 'docker_connect' script to connect
    command: sleep infinity  # keep container opened, commands will be executed in this existing same container

networks:
  no-internet:
    driver: bridge
    internal: true
